#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# DiggAI Anamnese — Production Database Setup Script
# Run from: anamnese-app/
# Usage:    DATABASE_URL="postgresql://..." bash scripts/migrate-production.sh
#
# IMPORTANT: Existing migrations were generated for SQLite (DATETIME syntax).
# For a FRESH PostgreSQL (Supabase) database, this script uses `prisma db push`
# to apply the current schema.prisma directly — bypassing the SQLite SQL files.
# After the push, the migration lock is corrected to postgresql and a baseline
# migration is created so future changes use `prisma migrate dev` normally.
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

# ─── Validate DATABASE_URL ────────────────────────────────────────────────────
if [[ -z "${DATABASE_URL:-}" ]]; then
  echo "ERROR: DATABASE_URL is not set."
  echo "Usage: DATABASE_URL='postgresql://...' bash scripts/migrate-production.sh"
  exit 1
fi

if [[ "${DATABASE_URL}" != postgresql* ]]; then
  echo "ERROR: DATABASE_URL must be a PostgreSQL connection string."
  echo "Got: ${DATABASE_URL:0:30}..."
  exit 1
fi

echo "=== DiggAI Production Database Setup ==="
echo "Target: ${DATABASE_URL:0:50}..."
echo ""

# ─── Step 1: Generate Prisma client ───────────────────────────────────────────
echo "[1/5] Generating Prisma client..."
npx prisma generate
echo "  OK"

# ─── Step 2: Apply schema to fresh database ───────────────────────────────────
echo ""
echo "[2/5] Applying schema to Supabase (prisma db push)..."
echo "  Note: Using db push instead of migrate deploy — existing migrations"
echo "  were generated for SQLite and are incompatible with PostgreSQL SQL syntax."
npx prisma db push --accept-data-loss
echo "  OK — Schema applied to PostgreSQL"

# ─── Step 3: Correct migration lock to postgresql ────────────────────────────
echo ""
echo "[3/5] Updating migration lock provider to postgresql..."
cat > prisma/migrations/migration_lock.toml << 'EOF'
# Please do not edit this file manually
# It should be added in your version-control system (e.g., Git)
provider = "postgresql"
EOF
echo "  OK — migration_lock.toml updated"

# ─── Step 4: Seed database ────────────────────────────────────────────────────
echo ""
echo "[4/5] Seeding database..."
echo "  This creates: demo-praxis tenant, admin/arzt/mfa users, 270+ questions"
npx prisma db seed
echo "  OK — Database seeded"

# ─── Step 5: Verify ──────────────────────────────────────────────────────────
echo ""
echo "[5/5] Verifying schema..."
npx prisma validate
echo "  OK — Schema valid"

echo ""
echo "=== Production Database Setup Complete ==="
echo ""
echo "NEXT STEPS:"
echo "  1. Commit the updated migration_lock.toml (git add prisma/migrations/migration_lock.toml)"
echo "  2. For future schema changes: npx prisma migrate dev --name <description>"
echo "  3. For future production deploys: npx prisma migrate deploy"
echo ""
echo "CREDENTIALS (from ARZT_PASSWORD env var — used by seed.ts):"
echo "  Admin:  username=admin       password=\${ARZT_PASSWORD}"
echo "  Arzt:   username=dr-mustermann password=\${ARZT_PASSWORD}"
echo "  MFA:    username=mfa          password=\${ARZT_PASSWORD}"
