param([string]$base = "$PSScriptRoot\..\public\locales")

$keys = @{
  de = @{
    "trust.badge.dsgvo"="DSGVO-konform";"trust.badge.encrypted"="Ende-zu-Ende verschluesselt";"trust.badge.doctor_only"="Nur Ihr Arzt sieht Ihre Daten";"trust.badge.non_commercial"="Keine kommerzielle Weitergabe";"trust.badge.aria_group"="Datenschutz- und Sicherheitszertifizierungen";"progress.step_of"="Schritt {{current}} von {{total}}";"progress.minutes_remaining"="Noch ~{{min}} Min.";"progress.saving"="Speichert...";"progress.saved"="Gespeichert";"progress.aria_label"="Fortschritt der Befragung";"progress.percent_label"="{{percent}}% der Fragen beantwortet";"progress.sr_description"="{{percent}} Prozent abgeschlossen, Schritt {{current}} von {{total}}: {{step}}";"progress.step.welcome"="Was bringt Sie heute herein?";"progress.step.details"="Ihre Beschwerden im Detail";"progress.step.history"="Ihre Vorerkrankungen";"progress.step.medications"="Medikamente und Allergien";"progress.step.symptoms"="Ihre Symptome";"progress.step.lifestyle"="Weitere Informationen";"progress.step.review"="Ueberpruefen und Absenden";"progress.step.final"="Abschluss";"progress.step.generic"="Schritt";"consent.heading"="Ihre Daten sind sicher";"consent.subheading"="Nur Ihr Behandlungsteam sieht Ihre Angaben.";"consent.subheading_doctor"="{{doctor}} wird Ihre Antworten persoenlich lesen.";"consent.time_estimate"="Dauert etwa {{min}} Minuten";"consent.group_label"="Ihre Einwilligung";"consent.required"="Erforderlich";"consent.optional"="Optional";"consent.more"="Mehr erfahren";"consent.less"="Weniger anzeigen";"consent.treatment.title"="Medizinische Behandlung";"consent.treatment.desc"="Ich willige in die Nutzung meiner Angaben fuer die Behandlung ein.";"consent.treatment.detail"="Rechtsgrundlage: DSGVO Art. 9 Abs. 2h.";"consent.data.title"="Datenverarbeitung fuer diesen Besuch";"consent.data.desc"="Meine Daten werden verschluesselt gespeichert.";"consent.data.detail"="AES-256-GCM verschluesselt. Keine kommerzielle Nutzung.";"consent.research.title"="Anonyme Qualitaetsforschung (optional)";"consent.research.desc"="Anonymisierte Nutzung zur Verbesserung der Versorgung.";"consent.research.detail"="Vollstaendig anonym. Kein Rueckschluss moeglich.";"consent.cta_ready"="Fragebogen starten";"consent.cta_waiting"="Bitte beide Pflichtfelder bestaetigen";"consent.privacy_link_prefix"="Mehr Infos in unserer";"consent.privacy_link"="Datenschutzerklaerung"
  }
  en = @{
    "trust.badge.dsgvo"="GDPR-compliant";"trust.badge.encrypted"="End-to-end encrypted";"trust.badge.doctor_only"="Only your doctor sees your data";"trust.badge.non_commercial"="No commercial sharing";"trust.badge.aria_group"="Privacy and security certifications";"progress.step_of"="Step {{current}} of {{total}}";"progress.minutes_remaining"="~{{min}} min left";"progress.saving"="Saving...";"progress.saved"="Saved";"progress.aria_label"="Survey progress";"progress.percent_label"="{{percent}}% of questions answered";"progress.sr_description"="{{percent}} percent complete, step {{current}} of {{total}}: {{step}}";"progress.step.welcome"="What brings you in today?";"progress.step.details"="Details of your complaints";"progress.step.history"="Your medical history";"progress.step.medications"="Medications and allergies";"progress.step.symptoms"="Your symptoms";"progress.step.lifestyle"="Additional information";"progress.step.review"="Review and submit";"progress.step.final"="Completion";"progress.step.generic"="Step";"consent.heading"="Your data is safe";"consent.subheading"="Only your care team sees your answers.";"consent.subheading_doctor"="{{doctor}} will personally read your answers before the appointment.";"consent.time_estimate"="Takes about {{min}} minutes";"consent.group_label"="Your consent";"consent.required"="Required";"consent.optional"="Optional";"consent.more"="Learn more";"consent.less"="Show less";"consent.treatment.title"="Medical treatment";"consent.treatment.desc"="I consent to my information being used for my treatment.";"consent.treatment.detail"="Legal basis: GDPR Art. 9(2)(h).";"consent.data.title"="Data processing for this visit";"consent.data.desc"="My data will be stored encrypted per GDPR.";"consent.data.detail"="AES-256-GCM encrypted. No commercial use.";"consent.research.title"="Anonymous quality research (optional)";"consent.research.desc"="I allow anonymized use of my data to improve care.";"consent.research.detail"="Fully anonymized. No identification possible.";"consent.cta_ready"="Start questionnaire";"consent.cta_waiting"="Please confirm both required fields";"consent.privacy_link_prefix"="More info in our";"consent.privacy_link"="Privacy Policy"
  }
  ar = @{
    "trust.badge.dsgvo"="متوافق مع GDPR";"trust.badge.encrypted"="مشفر من طرف الى طرف";"trust.badge.doctor_only"="طبيبك فقط يرى بياناتك";"trust.badge.non_commercial"="لا مشاركة تجارية";"trust.badge.aria_group"="شهادات الخصوصية والامان";"progress.step_of"="الخطوة {{current}} من {{total}}";"progress.minutes_remaining"="~{{min}} دقيقة متبقية";"progress.saving"="جارٍ الحفظ...";"progress.saved"="تم الحفظ";"progress.aria_label"="تقدم الاستبيان";"progress.percent_label"="{{percent}}% من الاسئلة تمت الاجابة";"progress.sr_description"="{{percent}} بالمئة مكتمل";"progress.step.welcome"="ما الذي يجلبك اليوم؟";"progress.step.details"="تفاصيل شكواك";"progress.step.history"="تاريخك الطبي";"progress.step.medications"="الادوية والحساسية";"progress.step.symptoms"="اعراضك";"progress.step.lifestyle"="معلومات اضافية";"progress.step.review"="المراجعة والارسال";"progress.step.final"="الاتمام";"progress.step.generic"="خطوة";"consent.heading"="بياناتك آمنة";"consent.subheading"="فريق رعايتك فقط يرى اجاباتك.";"consent.subheading_doctor"="سيقرا {{doctor}} اجاباتك شخصيا.";"consent.time_estimate"="يستغرق حوالي {{min}} دقائق";"consent.group_label"="موافقتك";"consent.required"="مطلوب";"consent.optional"="اختياري";"consent.more"="مزيد من المعلومات";"consent.less"="اظهار اقل";"consent.treatment.title"="العلاج الطبي";"consent.treatment.desc"="اوافق على استخدام معلوماتي للعلاج.";"consent.treatment.detail"="الاساس القانوني: المادة 9(2)(ح).";"consent.data.title"="معالجة البيانات لهذه الزيارة";"consent.data.desc"="سيتم تخزين بياناتي مشفرة.";"consent.data.detail"="AES-256-GCM. بدون استخدام تجاري.";"consent.research.title"="البحث النوعي المجهول (اختياري)";"consent.research.desc"="اسمح باستخدام بياناتي المجهولة.";"consent.research.detail"="مجهول تماماً. لا يمكن الاستدلال على الهوية.";"consent.cta_ready"="ابدا الاستبيان";"consent.cta_waiting"="يرجى تاكيد الحقلين المطلوبين";"consent.privacy_link_prefix"="مزيد من المعلومات في";"consent.privacy_link"="سياسة الخصوصية"
  }
  tr = @{
    "trust.badge.dsgvo"="GDPR uyumlu";"trust.badge.encrypted"="Uc uctan sifrelenmis";"trust.badge.doctor_only"="Verilerinizi sadece doktorunuz gorur";"trust.badge.non_commercial"="Ticari paylasim yok";"trust.badge.aria_group"="Gizlilik ve guvenlik sertifikalari";"progress.step_of"="Adim {{current}} / {{total}}";"progress.minutes_remaining"="~{{min}} dakika kaldi";"progress.saving"="Kaydediliyor...";"progress.saved"="Kaydedildi";"progress.aria_label"="Anket ilerlemesi";"progress.percent_label"="Sorularin {{percent}}% yaniti verildi";"progress.sr_description"="{{percent}} tamamlandi";"progress.step.welcome"="Bugun ne icin geldiniz?";"progress.step.details"="Sikayetlerinizin ayrintilari";"progress.step.history"="Tibbi gegmisiniz";"progress.step.medications"="Ilaclar ve alerjiler";"progress.step.symptoms"="Belirtileriniz";"progress.step.lifestyle"="Ek bilgiler";"progress.step.review"="Incele ve gonder";"progress.step.final"="Tamamlama";"progress.step.generic"="Adim";"consent.heading"="Verileriniz guvende";"consent.subheading"="Yanitlarinizi yalnizca bakim ekibiniz gorur.";"consent.subheading_doctor"="{{doctor}} yanitlarinizi kisisel olarak okuyacaktir.";"consent.time_estimate"="Yaklasik {{min}} dakika surer";"consent.group_label"="Onayiniz";"consent.required"="Zorunlu";"consent.optional"="Istege bagli";"consent.more"="Daha fazla bilgi";"consent.less"="Daha az goster";"consent.treatment.title"="Tibbi tedavi";"consent.treatment.desc"="Bilgilerimin tedaviim icin kullanilmasina izin veriyorum.";"consent.treatment.detail"="GDPR Madde 9(2)(h).";"consent.data.title"="Bu ziyaret icin veri isleme";"consent.data.desc"="Verilerim sifreli olarak saklanacak.";"consent.data.detail"="AES-256-GCM. Ticari kullanim yok.";"consent.research.title"="Anonim kalite arastirmasi (istege bagli)";"consent.research.desc"="Verilerimin anonimlestirilmis kullanimina izin veriyorum.";"consent.research.detail"="Tamamen anonim. Kimlik tespiti yapilamaz.";"consent.cta_ready"="Ankete basla";"consent.cta_waiting"="Lutfen her iki zorunlu alani onaylayin";"consent.privacy_link_prefix"="Daha fazla bilgi icin";"consent.privacy_link"="Gizlilik Politikasi"
  }
  uk = @{
    "trust.badge.dsgvo"="GDPR-vidpovidnyy";"trust.badge.encrypted"="Naskrizne shyfruvannya";"trust.badge.doctor_only"="Vashi dani bachyt tilky likar";"trust.badge.non_commercial"="Bez komertsiynogo poshyrennya";"trust.badge.aria_group"="Sertyfikaty konfidentsiynosti";"progress.step_of"="Krok {{current}} z {{total}}";"progress.minutes_remaining"="~{{min}} khv. zal.";"progress.saving"="Zberehennya...";"progress.saved"="Zberezheno";"progress.aria_label"="Prohres opytuvannya";"progress.percent_label"="{{percent}}% pytan";"progress.sr_description"="{{percent}}% zaversheno";"progress.step.welcome"="Shcho prynevshy vas sohodni?";"progress.step.details"="Detali skarhy";"progress.step.history"="Medychna istoriya";"progress.step.medications"="Liky ta alerhi";"progress.step.symptoms"="Symptomy";"progress.step.lifestyle"="Dodatkova info";"progress.step.review"="Perevirka";"progress.step.final"="Zavershennya";"progress.step.generic"="Krok";"consent.heading"="Vashi dani v bezpetsi";"consent.subheading"="Tilky vasha komanda bachyt vidpovidi.";"consent.subheading_doctor"="{{doctor}} prochytaye vidpovidi osobysto.";"consent.time_estimate"="Tryvaye blyzko {{min}} khv.";"consent.group_label"="Vasha zghoda";"consent.required"="Obovyazkovo";"consent.optional"="Neobovyazkovo";"consent.more"="Bilshe";"consent.less"="Menshe";"consent.treatment.title"="Medychne likuvannya";"consent.treatment.desc"="Poghodzhuysya na vykorystannya danykh.";"consent.treatment.detail"="GDPR St. 9(2)(h).";"consent.data.title"="Obrobka danykh";"consent.data.desc"="Dani zberizayutsya u zashufrovaniy formi.";"consent.data.detail"="AES-256-GCM. Bez komertsiyi.";"consent.research.title"="Anonimne doslidzhennya (neobovyazkovo)";"consent.research.desc"="Dozvolyayu anonimne vykorystannya.";"consent.research.detail"="Povnistyu anonimy. Identyfikatsiya nemożlyva.";"consent.cta_ready"="Pochaty anketu";"consent.cta_waiting"="Pidtverdzt obydva polya";"consent.privacy_link_prefix"="Bilshe v nashiy";"consent.privacy_link"="Politytsi konf."
  }
  es = @{
    "trust.badge.dsgvo"="Cumple el RGPD";"trust.badge.encrypted"="Cifrado extremo a extremo";"trust.badge.doctor_only"="Solo su medico ve sus datos";"trust.badge.non_commercial"="Sin uso comercial";"trust.badge.aria_group"="Certificaciones de privacidad";"progress.step_of"="Paso {{current}} de {{total}}";"progress.minutes_remaining"="~{{min}} min restantes";"progress.saving"="Guardando...";"progress.saved"="Guardado";"progress.aria_label"="Progreso del cuestionario";"progress.percent_label"="{{percent}}% respondidas";"progress.sr_description"="{{percent}} por ciento completo";"progress.step.welcome"="Que le trae hoy?";"progress.step.details"="Detalles de su queja";"progress.step.history"="Su historial medico";"progress.step.medications"="Medicamentos y alergias";"progress.step.symptoms"="Sus sintomas";"progress.step.lifestyle"="Informacion adicional";"progress.step.review"="Revisar y enviar";"progress.step.final"="Finalizacion";"progress.step.generic"="Paso";"consent.heading"="Sus datos estan seguros";"consent.subheading"="Solo su equipo de atencion ve sus respuestas.";"consent.subheading_doctor"="{{doctor}} leera sus respuestas personalmente.";"consent.time_estimate"="Tarda unos {{min}} minutos";"consent.group_label"="Su consentimiento";"consent.required"="Obligatorio";"consent.optional"="Opcional";"consent.more"="Mas informacion";"consent.less"="Mostrar menos";"consent.treatment.title"="Tratamiento medico";"consent.treatment.desc"="Consiento el uso de mi informacion para mi tratamiento.";"consent.treatment.detail"="RGPD Art. 9(2)(h).";"consent.data.title"="Tratamiento de datos";"consent.data.desc"="Mis datos se almacenaran cifrados.";"consent.data.detail"="AES-256-GCM. Sin uso comercial.";"consent.research.title"="Investigacion anonima (opcional)";"consent.research.desc"="Permito el uso anonimizado de mis datos.";"consent.research.detail"="Completamente anonimizado.";"consent.cta_ready"="Iniciar cuestionario";"consent.cta_waiting"="Confirme ambos campos obligatorios";"consent.privacy_link_prefix"="Mas informacion en nuestra";"consent.privacy_link"="Politica de privacidad"
  }
  fa = @{
    "trust.badge.dsgvo"="مطابق GDPR";"trust.badge.encrypted"="رمزگذاری سرتاسری";"trust.badge.doctor_only"="فقط پزشک شما داده هایتان را می بیند";"trust.badge.non_commercial"="بدون اشتراک گذاری تجاری";"trust.badge.aria_group"="گواهینامه های حریم خصوصی";"progress.step_of"="مرحله {{current}} از {{total}}";"progress.minutes_remaining"="~{{min}} دقیقه مانده";"progress.saving"="در حال ذخیره...";"progress.saved"="ذخیره شد";"progress.aria_label"="پیشرفت پرسشنامه";"progress.percent_label"="{{percent}} درصد";"progress.sr_description"="{{percent}} درصد تکمیل";"progress.step.welcome"="امروز برای چه آمده اید؟";"progress.step.details"="جزئیات شکایت";"progress.step.history"="سابقه پزشکی";"progress.step.medications"="داروها و آلرژی";"progress.step.symptoms"="علائم";"progress.step.lifestyle"="اطلاعات بیشتر";"progress.step.review"="بررسی و ارسال";"progress.step.final"="تکمیل";"progress.step.generic"="مرحله";"consent.heading"="داده های شما در امنیت است";"consent.subheading"="فقط تیم درمانی پاسخ هایتان را می بیند.";"consent.subheading_doctor"="{{doctor}} پاسخ ها را شخصاً می خواند.";"consent.time_estimate"="حدود {{min}} دقیقه";"consent.group_label"="رضایت شما";"consent.required"="الزامی";"consent.optional"="اختیاری";"consent.more"="اطلاعات بیشتر";"consent.less"="کمتر";"consent.treatment.title"="درمان پزشکی";"consent.treatment.desc"="موافقت می کنم با استفاده از اطلاعاتم.";"consent.treatment.detail"="GDPR ماده 9(2).";"consent.data.title"="پردازش داده";"consent.data.desc"="داده ها رمزگذاری می شوند.";"consent.data.detail"="AES-256-GCM. بدون استفاده تجاری.";"consent.research.title"="تحقیق ناشناس (اختیاری)";"consent.research.desc"="اجازه استفاده ناشناس از داده ها.";"consent.research.detail"="کاملاً ناشناس.";"consent.cta_ready"="شروع پرسشنامه";"consent.cta_waiting"="لطفاً هر دو فیلد الزامی را تأیید کنید";"consent.privacy_link_prefix"="اطلاعات بیشتر در";"consent.privacy_link"="سیاست حریم خصوصی"
  }
  it = @{
    "trust.badge.dsgvo"="Conforme al GDPR";"trust.badge.encrypted"="Crittografato end-to-end";"trust.badge.doctor_only"="Solo il suo medico vede i suoi dati";"trust.badge.non_commercial"="Nessuna condivisione commerciale";"trust.badge.aria_group"="Certificazioni privacy e sicurezza";"progress.step_of"="Passo {{current}} di {{total}}";"progress.minutes_remaining"="~{{min}} min rimasti";"progress.saving"="Salvataggio...";"progress.saved"="Salvato";"progress.aria_label"="Progresso del questionario";"progress.percent_label"="{{percent}}% domande con risposta";"progress.sr_description"="{{percent}} percento completato";"progress.step.welcome"="Cosa la porta oggi?";"progress.step.details"="Dettagli del disturbo";"progress.step.history"="Storia medica";"progress.step.medications"="Farmaci e allergie";"progress.step.symptoms"="Sintomi";"progress.step.lifestyle"="Ulteriori informazioni";"progress.step.review"="Revisione e invio";"progress.step.final"="Completamento";"progress.step.generic"="Passo";"consent.heading"="I suoi dati sono al sicuro";"consent.subheading"="Solo il suo team di cura vede le sue risposte.";"consent.subheading_doctor"="{{doctor}} leggera le sue risposte prima dell'appuntamento.";"consent.time_estimate"="Richiede circa {{min}} minuti";"consent.group_label"="Il suo consenso";"consent.required"="Obbligatorio";"consent.optional"="Facoltativo";"consent.more"="Ulteriori informazioni";"consent.less"="Mostra meno";"consent.treatment.title"="Trattamento medico";"consent.treatment.desc"="Acconsento all'utilizzo delle mie informazioni.";"consent.treatment.detail"="GDPR Art. 9(2)(h).";"consent.data.title"="Elaborazione dati";"consent.data.desc"="I miei dati saranno archiviati crittografati.";"consent.data.detail"="AES-256-GCM. Nessun uso commerciale.";"consent.research.title"="Ricerca qualita anonima (facoltativa)";"consent.research.desc"="Permetto uso anonimizzato dei miei dati.";"consent.research.detail"="Completamente anonimizzato.";"consent.cta_ready"="Avvia questionario";"consent.cta_waiting"="Confirmi entrambi i campi obbligatori";"consent.privacy_link_prefix"="Ulteriori informazioni nella nostra";"consent.privacy_link"="Informativa sulla privacy"
  }
  fr = @{
    "trust.badge.dsgvo"="Conforme au RGPD";"trust.badge.encrypted"="Chiffrement de bout en bout";"trust.badge.doctor_only"="Seul votre medecin voit vos donnees";"trust.badge.non_commercial"="Pas de partage commercial";"trust.badge.aria_group"="Certifications confidentialite et securite";"progress.step_of"="Etape {{current}} sur {{total}}";"progress.minutes_remaining"="~{{min}} min restantes";"progress.saving"="Enregistrement...";"progress.saved"="Enregistre";"progress.aria_label"="Progression du questionnaire";"progress.percent_label"="{{percent}}% des questions repondues";"progress.sr_description"="{{percent}} pour cent complete";"progress.step.welcome"="Qu'est-ce qui vous amene aujourd'hui?";"progress.step.details"="Details de votre plainte";"progress.step.history"="Antecedents medicaux";"progress.step.medications"="Medicaments et allergies";"progress.step.symptoms"="Symptomes";"progress.step.lifestyle"="Informations complementaires";"progress.step.review"="Verifier et envoyer";"progress.step.final"="Finalisation";"progress.step.generic"="Etape";"consent.heading"="Vos donnees sont securisees";"consent.subheading"="Seule votre equipe soignante voit vos reponses.";"consent.subheading_doctor"="{{doctor}} lira vos reponses personnellement.";"consent.time_estimate"="Prend environ {{min}} minutes";"consent.group_label"="Votre consentement";"consent.required"="Obligatoire";"consent.optional"="Optionnel";"consent.more"="En savoir plus";"consent.less"="Afficher moins";"consent.treatment.title"="Traitement medical";"consent.treatment.desc"="Je consens a l'utilisation de mes informations pour mon traitement.";"consent.treatment.detail"="RGPD Art. 9(2)(h).";"consent.data.title"="Traitement des donnees";"consent.data.desc"="Mes donnees seront stockees de maniere chiffree.";"consent.data.detail"="AES-256-GCM. Pas d'utilisation commerciale.";"consent.research.title"="Recherche qualitative anonyme (optionnel)";"consent.research.desc"="Je permets l'utilisation anonymisee de mes donnees.";"consent.research.detail"="Entierement anonymisees.";"consent.cta_ready"="Demarrer le questionnaire";"consent.cta_waiting"="Veuillez confirmer les deux champs obligatoires";"consent.privacy_link_prefix"="Plus d'informations dans notre";"consent.privacy_link"="Politique de confidentialite"
  }
  pl = @{
    "trust.badge.dsgvo"="Zgodny z RODO";"trust.badge.encrypted"="Szyfrowanie end-to-end";"trust.badge.doctor_only"="Tylko Twoj lekarz widzi Twoje dane";"trust.badge.non_commercial"="Brak udostepniania komercyjnego";"trust.badge.aria_group"="Certyfikaty prywatnosci i bezpieczenstwa";"progress.step_of"="Krok {{current}} z {{total}}";"progress.minutes_remaining"="~{{min}} min pozostalo";"progress.saving"="Zapisywanie...";"progress.saved"="Zapisano";"progress.aria_label"="Postep ankiety";"progress.percent_label"="{{percent}}% pytan";"progress.sr_description"="{{percent}} procent ukonczone";"progress.step.welcome"="Co Cie do nas sprowadza?";"progress.step.details"="Szczegoly dolegliwosci";"progress.step.history"="Historia medyczna";"progress.step.medications"="Leki i alergie";"progress.step.symptoms"="Objawy";"progress.step.lifestyle"="Dodatkowe informacje";"progress.step.review"="Przejrzenie i wyslanie";"progress.step.final"="Zakonczenie";"progress.step.generic"="Krok";"consent.heading"="Twoje dane sa bezpieczne";"consent.subheading"="Tylko Twoj zespol opieki widzi Twoje odpowiedzi.";"consent.subheading_doctor"="{{doctor}} osobiscie przeczyta Twoje odpowiedzi.";"consent.time_estimate"="Zajmuje okolo {{min}} minut";"consent.group_label"="Twoja zgoda";"consent.required"="Wymagane";"consent.optional"="Opcjonalne";"consent.more"="Dowiedz sie wiecej";"consent.less"="Pokaz mniej";"consent.treatment.title"="Leczenie medyczne";"consent.treatment.desc"="Wyrazam zgode na wykorzystanie moich danych.";"consent.treatment.detail"="RODO Art. 9(2)(h).";"consent.data.title"="Przetwarzanie danych";"consent.data.desc"="Moje dane beda przechowywane zaszyfrowane.";"consent.data.detail"="AES-256-GCM. Bez uzycia komercyjnego.";"consent.research.title"="Anonimowe badania jakosci (opcjonalne)";"consent.research.desc"="Zezwalam na anonimowe wykorzystanie moich danych.";"consent.research.detail"="Calkowicie zanonimizowane.";"consent.cta_ready"="Rozpocznij ankiete";"consent.cta_waiting"="Prosze potwierdzic oba wymagane pola";"consent.privacy_link_prefix"="Wiecej informacji w naszej";"consent.privacy_link"="Polityce prywatnosci"
  }
  ru = @{
    "trust.badge.dsgvo"="Sootvetstvuet GDPR";"trust.badge.encrypted"="Skvoznoe shifrovanie";"trust.badge.doctor_only"="Vashi dannye vidit tolko vrach";"trust.badge.non_commercial"="Bez kommercheskoy peredachi";"trust.badge.aria_group"="Sertifikaty bezopasnosti";"progress.step_of"="Shag {{current}} iz {{total}}";"progress.minutes_remaining"="~{{min}} min ostalos'";"progress.saving"="Sokhranenie...";"progress.saved"="Sokhraneno";"progress.aria_label"="Progress oprosa";"progress.percent_label"="{{percent}}% voprosov s otvetom";"progress.sr_description"="{{percent}} procentov";"progress.step.welcome"="Chto vas bespokoit?";"progress.step.details"="Podrobnosti zhaloby";"progress.step.history"="Istoriya bolezni";"progress.step.medications"="Lekarstva i allergii";"progress.step.symptoms"="Simptomy";"progress.step.lifestyle"="Dopolnitelnaya informatsiya";"progress.step.review"="Proverit i otpravit";"progress.step.final"="Zavershenie";"progress.step.generic"="Shag";"consent.heading"="Vashi dannye v bezopasnosti";"consent.subheading"="Tolko vashe lechebnoe komanda vidit otvety.";"consent.subheading_doctor"="{{doctor}} lichno prochitaet otvety.";"consent.time_estimate"="Zaymet okolo {{min}} minut";"consent.group_label"="Vashe soglasie";"consent.required"="Obyazatelno";"consent.optional"="Neobyazatelno";"consent.more"="Uznat bolshe";"consent.less"="Pokazat menshe";"consent.treatment.title"="Meditsinskoe lechenie";"consent.treatment.desc"="Soglasiya na ispolzovanie dannykh.";"consent.treatment.detail"="GDPR St. 9(2)(h).";"consent.data.title"="Obrabotka dannykh";"consent.data.desc"="Dannye khranitsya v zashifrovamnom vide.";"consent.data.detail"="AES-256-GCM. Bez kommercheskogo ispolzovaniya.";"consent.research.title"="Anonimnoe issledovanie (neobyazatelno)";"consent.research.desc"="Razreshayu anonimnoe ispolzovanie dannykh.";"consent.research.detail"="Polnostyu anonimizirovano.";"consent.cta_ready"="Nachat anketu";"consent.cta_waiting"="Podtverdite oba polyay";"consent.privacy_link_prefix"="Podrobnee v nashey";"consent.privacy_link"="Politike konfidentsialnosti"
  }
}

$ok = 0; $fail = 0
foreach ($lang in $keys.Keys) {
  $file = Join-Path $base "$lang\translation.json"
  try {
    $obj = Get-Content $file -Raw -Encoding UTF8 | ConvertFrom-Json
    foreach ($k in $keys[$lang].Keys) {
      $obj | Add-Member -MemberType NoteProperty -Name $k -Value $keys[$lang][$k] -Force
    }
    $obj | ConvertTo-Json -Depth 10 | Set-Content $file -Encoding UTF8
    Write-Output "OK: $lang"
    $ok++
  } catch {
    Write-Output "FAIL: $lang - $_"
    $fail++
  }
}
Write-Output "DONE: $ok ok, $fail fail"
